language: java
jdk:
  - oraclejdk8
script:
  - mvn install
notifications:
  email: false
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "target/*.jar"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
