language: java
jdk:
 - oraclejdk8
script:
  - mvn clean install
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "dist/CommandBus-1.2.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: false
