language: java
jdk:
 - oraclejdk8
script:
  - mvn clean install
  - make dist
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true
